export const storylineSeed = {
  id: "storyline-main",
  scenarios: [
    {
      id: "part-i-opener",
      label: "Part I Opener",
      defaultMode: "story",
      startStep: "survive-in-the-woods",
      steps: [
        {
          id: "survive-in-the-woods",
          objective: "Keep moving. Find something that can help you survive.",
          beat: "intro",
          allowed: {
            movement: { mode: "unrestricted", hexes: ["east-pines"] },
            storyForwardActions: ["move-hex:east-pines"],
          },
          completesWhen: { location: { place: "outdoors", hex: "east-pines" } },
          next: "keep-moving-west",
        },
        {
          id: "keep-moving-west",
          objective: "Keep moving. Stay across the slope.",
          beat: "east-pines",
          allowed: {
            movement: { mode: "unrestricted", hexes: ["center-pines"] },
            storyForwardActions: ["move-hex:center-pines"],
          },
          completesWhen: { location: { place: "outdoors", hex: "center-pines" } },
          next: "reach-the-gate",
        },
        {
          id: "reach-the-gate",
          objective: "Follow the fence. Find where it leads.",
          beat: "center-pines",
          allowed: {
            movement: {
              mode: "unrestricted",
              hexes: ["north-bend", "gate-woods"],
            },
            storyForwardActions: ["move-hex:north-bend", "route:gate-woods", "move-hex:gate-woods"],
          },
          completesWhen: { location: { place: "outdoors", hex: "gate-woods" } },
          nextScenario: "part-i-station",
        },
      ],
    },
    {
      id: "part-i-station",
      label: "Part I Station",
      defaultMode: "story",
      startStep: "find-a-way-past-fence",
      steps: [
        {
          id: "find-a-way-past-fence",
          objective: "Find a way past the fence.",
          beat: "the-gate",
          allowed: {
            movement: {
              mode: "unrestricted",
              hexes: ["south-pines", "west-slope", "utility-yard"],
            },
            storyForwardActions: [
              "passage-toggle:compound-gate",
              "passage:compound-gate",
              "search:barrier",
              "passage:south-pines-hole",
              "move-hex:west-slope",
              "route:utility-yard",
              "move-hex:utility-yard",
              "barrier:utility-yard",
            ],
            outdoorActions: [
              "search:barrier",
              "passage-toggle:compound-gate",
              "passage:compound-gate",
              "passage:south-pines-hole",
            ],
          },
          completesWhen: { location: { place: "outdoors", hex: "utility-yard" } },
          next: "look-for-shelter",
        },
        {
          id: "look-for-shelter",
          objective: "Look for shelter before you run out of light.",
          beat: "large-bay-man-front",
          allowed: {
            movement: {
              mode: "local-area",
              exteriorNodes: ["garage-front-entrance", "large-bay-man-front", "south-east-corner-entrance"],
              transitions: ["garage-exit", "man-door-path", "southeast-corner"],
            },
            storyForwardActions: [
              "move-exterior:large-bay-man-front",
              "door-break:large-bay-man",
              "door-open:large-bay-man",
              "move-room:large-bay",
            ],
            indoorActions: ["door-break:large-bay-man", "door-open:large-bay-man"],
          },
          completesWhen: { location: { place: "indoors", room: "large-bay" } },
          next: "solve-first-crisis",
        },
        {
          id: "solve-first-crisis",
          objective: "Find food, water, and somewhere safe to rest.",
          beat: "large-bay",
          allowed: {
            movement: {
              mode: "local-area",
              rooms: ["garage-stair", "conference", "kitchen", "library"],
            },
            storyForwardActions: [
              "move-room:kitchen",
              "action:eat-rations",
              "action:purify-water",
              "move-room:library",
              "action:rest-in-library",
            ],
            indoorActions: ["eat-rations", "purify-water", "rest-in-library"],
          },
          completesWhen: { flag: "day1.complete" },
          next: "understand-building",
        },
        {
          id: "understand-building",
          objective: "Figure out what this building was for.",
          beat: "control-room",
          allowed: {
            movement: { mode: "local-area", rooms: ["control-room"] },
            storyForwardActions: ["move-room:control-room", "action:read-hydro-startup-card"],
            stageViews: [{ kind: "document", id: "hydro-startup-instruction-card" }],
            indoorActions: ["read-hydro-startup-card"],
            itemActions: ["hydro-startup-instruction-card.read"],
          },
          completesWhen: { flag: "hydro.startup_card_read" },
          next: "inspect-intake",
        },
        {
          id: "inspect-intake",
          objective: "Trace the water path outside.",
          beat: "intake-entrance",
          allowed: {
            movement: {
              mode: "local-area",
              hexes: ["utility-yard"],
              exteriorNodes: ["upstream-bank", "intake-entrance"],
            },
            storyForwardActions: ["move-exterior:upstream-bank", "move-exterior:intake-entrance"],
          },
          completesWhen: { location: { place: "indoors", exteriorNode: "upstream-bank" } },
          next: "clear-open-intake",
        },
        {
          id: "clear-open-intake",
          objective: "Clear debris and open the intake.",
          beat: "intake-entrance",
          allowed: {
            movement: { mode: "local-area" },
            storyForwardActions: ["action:clear-intake-debris", "action:open-intake"],
            indoorActions: ["clear-intake-debris", "open-intake"],
          },
          completesWhen: { facility: { "hydro.intakeOpen": true } },
          next: "align-diversion-valve",
        },
        {
          id: "align-diversion-valve",
          objective: "Align the upstream diversion valve.",
          beat: "midstream-bank",
          allowed: {
            movement: { mode: "local-area" },
            storyForwardActions: ["move-exterior:midstream-bank", "action:align-pipeflow"],
            indoorActions: ["align-pipeflow"],
          },
          completesWhen: { facility: { "hydro.manualValves.upstreamOpen": true } },
          next: "open-turbine-valve",
        },
        {
          id: "open-turbine-valve",
          objective: "Open the powerhouse pipe valve.",
          beat: "downstream-bank",
          allowed: {
            movement: { mode: "local-area" },
            storyForwardActions: ["move-exterior:downstream-bank", "action:open-turbine-valve"],
            indoorActions: ["open-turbine-valve"],
          },
          completesWhen: { facility: { "hydro.manualValves.powerhouseOpen": true } },
          next: "return-control-room",
        },
        {
          id: "return-control-room",
          objective: "Return to the control room.",
          beat: "control-room",
          allowed: {
            movement: {
              mode: "local-area",
              rooms: ["control-room"],
            },
            storyForwardActions: ["move-room:control-room"],
          },
          completesWhen: { location: { place: "indoors", room: "control-room" } },
          next: "connect-power",
        },
        {
          id: "connect-power",
          objective: "Connect station power.",
          beat: "control-room",
          allowed: {
            movement: { mode: "current-location-only" },
            storyForwardActions: ["action:connect-power"],
            indoorActions: ["connect-power"],
          },
          completesWhen: { facility: { "hydro.online": true } },
          next: "check-console",
        },
        {
          id: "check-console",
          objective: "Check the generator console.",
          beat: "control-room",
          allowed: {
            movement: { mode: "current-location-only" },
            storyForwardActions: ["hydro-console:open"],
            stageViews: [{ kind: "console", id: "hydro" }],
          },
          onEnter: {
            view: { kind: "console", id: "hydro", focus: "generation" },
          },
          completesWhen: { facility: { "hydro.online": true } },
          next: "complete-startup",
        },
        {
          id: "complete-startup",
          objective: "Bring the hydro generator online.",
          beat: "control-room",
          allowed: { movement: { mode: "unrestricted" } },
          completesWhen: { facility: { "hydro.startupComplete": true } },
          next: null,
        },
      ],
    },
  ],
};
